name: FancyCrafting
version: 4.11.0
main: de.ancash.fancycrafting.FancyCrafting
depend: [ILibrary]
soft-depend: [CustomCrafting]
author: [Ancash]
api-version: 1.13

commands:
   fc:
      description: Main FancyCrafting command
      aliases: [fancycrafting, craft]
      usage: "§cUsage: /fc help"